# Generated by Django 4.1.2 on 2022-10-12 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=200)),
                ('name', models.CharField(default='New Album', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
