# Generated by Django 4.1.2 on 2022-10-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
