# Generated by Django 4.1.2 on 2022-10-26 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album'), max_length=200)),
                ('image', models.ImageField(upload_to='./media/images')),
                ('audio', models.FileField(upload_to='./media/audio', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])])),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
            ],
        ),
    ]
