# Generated by Django 4.1.2 on 2022-10-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='IsVerified',
            field=models.BooleanField(default=False),
        ),
    ]
