# Generated by Django 4.1.2 on 2022-10-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_options_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album_name',
            new_name='album',
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
