# Generated by Django 4.1.2 on 2022-10-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='IsVerified',
            field=models.BooleanField(default=False, help_text='Approve the album'),
        ),
    ]
