# Generated by Django 4.1.2 on 2022-10-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_album_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='IsVerified',
        ),
        migrations.AddField(
            model_name='album',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
    ]
