# Generated by Django 4.1.2 on 2022-10-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('stage_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('social_link', models.CharField(max_length=100)),
                ('albums', models.ManyToManyField(blank=True, to='albums.album')),
            ],
        ),
    ]
